services:
  - type: web
    name: mm-screener
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_USER
        value: admin
      - key: FLASK_PASS
        value: MMscreener
